version: '3'

services:
  app:
    build: .
    container_name: app
    command: ['./rails.sh']
    volumes: 
      - '.:/test_coding'
    ports: 
     - '3000:3000'
    depends_on: 
      - db
  db:
    image: postgres:10.6-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data